# Plugin dependencies for development/testing only.
# Users of this plugin don't need these - they configure ForgeTool in their .plzconfig.

# Uncomment if testing the plugin standalone:
# plugin_repo(
#     name = "go",
#     revision = "v1.17.3",
# )
