# Plugin dependencies for development/testing only.
# Users of this plugin don't need these - they configure ForgeTool in their .plzconfig.

plugin_repo(
    name = "go",
    revision = "v1.28.2",
)

plugin_repo(
    name = "cc",
    revision = "v0.7.0",
)
